myRepo:
  gitProvider: ych_github_pipe
  path: cyan21/test-pipelines
jpdIntegrationName:
  - yann_platform_token
  - yannsbx_platform_access

# automation config
yqVersion: v4.27.5
automationRepo: jfrog-automation
statusFile: status.yml
from: SAAS_DR
to: SAAS_MAIN