template: true   # required for local templates.
valuesFilePath: ./values.yml

pipelines:
  - name: syncDR
    configuration:
      jfrogCliVersion: 2
      affinityGroup: together
      environmentVariables: 
        readOnly:
          JFROG_CLI_PLUGINS_SERVER: {{ .Values.jpdMain }}
          JFROG_CLI_PLUGINS_REPO: jfrog-automation
          JF_PLUGIN_REPOSYNC_INVENTORY_PATH: /tmp
    steps:
      - name: Ping
        type: utils/ping
        configuration:
          #affinityGroup: together
          inputResources:
            - name: main_site_update
          integrations:
          # {{- range .Values.jpdIntegrationName }}
          #   - name: "{{ . }}"
          # {{- end }}
            - name: {{ .Values.jpdMain }}
            - name: {{ .Values.jpdDr }}
          iteration: 2
          sleepBetweenIteration: 5
      - name: checkOutages
        type: utils/bashV2
        configuration:
          #affinityGroup: together
          inputSteps:
            - name: Ping
          integrations:
            - name: {{ .Values.jpdDr }}
        execution:
          onExecute:
            - requestDateTime=$(jf rt s {{ .Values.automationRepo }}/{{ .Values.statusFile }} | jq -r ".[].props.requestDateTime[]")
            - |
              if [[ $requestDateTime -eq "" ]]; then 
                echo "[WARN] {{ .Values.statusFile }} NOT found or "requestDateTime" properties could NOT be found . Check if the Health Check pipeline has run on the DR side"
                exit 1              
              fi
            - canUpdateDR=$(jf rt s {{ .Values.automationRepo }}/{{ .Values.statusFile }} | jq -r ".[].props.canUpdateDR[]")
            - |
              if [[ $? -eq "" ]]; then 
                echo "[WARN] "canUpdateDR" properties could NOT be found . Check if the Health Check pipeline has run on the DR side"
                exit 1              
              fi            
            - epochNow=$(date +%s)
            - echo $canUpdateDR
            - interval=$(expr $epochNow - $requestDateTime)
            - echo $epochNow
            - echo $requestDateTime
            - echo $interval
            - |
              if [[ $interval -gt {{ .Values.HealthCheckIntervalInSec }} ]] ; then 
                  echo "[ERROR] the last update on the  {{ .Values.automationRepo }}/{{ .Values.statusFile }} was more than {{ .Values.HealthCheckIntervalInSec }} seconds."
                  exit 1
              fi 
            - |
              if [[ $canUpdateDR == "false" ]] ; then
                  echo "[WARN] File {{ .Values.automationRepo }}/{{ .Values.statusFile }} : canUpdateDR=false; No sync will be pushed to the DR."
                  exit 2
              fi
      - name: CreateUpdateProjects
        type: utils/bashV2
        configuration:
          #affinityGroup: together
          inputSteps:
            - name: checkOutages
          integrations:
            - name: {{ .Values.jpdMain }}
            - name: {{ .Values.jpdDr }}
          cliPlugin: "{{ .Values.projectPlugin.name }}@{{ .Values.projectPlugin.version }}"     
        execution:
          onExecute:
            - /root/.jfrog/plugins/proj-sync/bin/{{ .Values.projectPlugin.name }} diff create {{ .Values.jpdMain }} {{ .Values.jpdDr }}
      - name: createLocalRepositories
        type: utils/bashV2
        configuration:
          #affinityGroup: together
          inputSteps:
            - name: CreateUpdateProjects
          integrations:
            - name: {{ .Values.jpdMain }}
            - name: {{ .Values.jpdDr }}
          cliPlugin: "{{ .Values.cliPlugin.name }}@{{ .Values.cliPlugin.version }}"
        execution:
          onExecute:
            - jf c s
            - jf {{ .Values.cliPlugin.name }} -v 
            - jf {{ .Values.cliPlugin.name }} create local {{ .Values.jpdMain }} {{ .Values.jpdDr }} --dry-run=false --inventory=false
      - name: createRemoteRepositories
        type: utils/bashV2
        configuration:
          #affinityGroup: together
          inputSteps:
            - name: CreateUpdateProjects
          integrations:
            - name: {{ .Values.jpdMain }}
            - name: {{ .Values.jpdDr }}
          cliPlugin: "{{ .Values.cliPlugin.name }}@{{ .Values.cliPlugin.version }}"
        execution:
          onExecute:
            - jf {{ .Values.cliPlugin.name }} create remote {{ .Values.jpdMain }} {{ .Values.jpdDr }} --dry-run=false --inventory=false
      - name: createVirtualRepositories
        type: utils/bashV2
        configuration:
          # affinityGroup: CreateUpdateProjects
          inputSteps:
            - name: createLocalRepositories
            - name: createRemoteRepositories
          integrations:
            - name: {{ .Values.jpdMain }}
            - name: {{ .Values.jpdDr }}
          cliPlugin: "{{ .Values.cliPlugin.name }}@{{ .Values.cliPlugin.version }}"     
        execution:
          onExecute:
            - jf {{ .Values.cliPlugin.name }} create virtual {{ .Values.jpdMain }} {{ .Values.jpdDr }} --dry-run=false --inventory=false      
      - name: UpdateLocalRepositories
        type: utils/bashV2
        configuration:
          #affinityGroup: together
          inputSteps:
            - name: createVirtualRepositories
          integrations:
            - name: {{ .Values.jpdMain }}
            - name: {{ .Values.jpdDr }}
          cliPlugin: "{{ .Values.cliPlugin.name }}@{{ .Values.cliPlugin.version }}"
        execution:
          onExecute:
            - jf c s
            - jf {{ .Values.cliPlugin.name }} -v 
            - jf {{ .Values.cliPlugin.name }} update local {{ .Values.jpdMain }} {{ .Values.jpdDr }} --dry-run=false 
      - name: updateRemoteRepositories
        type: utils/bashV2
        configuration:
          #affinityGroup: together
          inputSteps:
            - name: createVirtualRepositories
          integrations:
            - name: {{ .Values.jpdMain }}
            - name: {{ .Values.jpdDr }}
          cliPlugin: "{{ .Values.cliPlugin.name }}@{{ .Values.cliPlugin.version }}"
        execution:
          onExecute:
            - jf {{ .Values.cliPlugin.name }} update remote {{ .Values.jpdMain }} {{ .Values.jpdDr }} --dry-run=false 
      - name: updateVirtualRepositories
        type: utils/bashV2
        configuration:
          # affinityGroup: together
          inputSteps:
            - name: UpdateLocalRepositories
            - name: updateRemoteRepositories
          integrations:
            - name: {{ .Values.jpdMain }}
            - name: {{ .Values.jpdDr }}
          cliPlugin: "{{ .Values.cliPlugin.name }}@{{ .Values.cliPlugin.version }}"     
        execution:
          onExecute:
            - jf {{ .Values.cliPlugin.name }} create virtual {{ .Values.jpdMain }} {{ .Values.jpdDr }} --dry-run=false 
      - name: deleteLocalRepositories
        type: utils/bashV2
        configuration:
          #affinityGroup: together
          inputSteps:
            - name: updateVirtualRepositories
          integrations:
            - name: {{ .Values.jpdMain }}
            - name: {{ .Values.jpdDr }}
          cliPlugin: "{{ .Values.cliPlugin.name }}@{{ .Values.cliPlugin.version }}"
        execution:
          onExecute:
            - jf {{ .Values.cliPlugin.name }} -v
            - jf {{ .Values.cliPlugin.name }} delete local {{ .Values.jpdMain }} {{ .Values.jpdDr }} --dry-run=false --inventory=true
          onSuccess:
            - cd $JF_PLUGIN_REPOSYNC_INVENTORY_PATH && ls -l       
            - mkdir {{ .Values.jpdDr }} && mv inventory*.yaml {{ .Values.jpdDr }}/
            - jf rt u {{ .Values.jpdDr }}/* $JFROG_CLI_PLUGINS_REPO/
            - rm -rf {{ .Values.jpdDr }}
      - name: deleteRemoteRepositories
        type: utils/bashV2
        configuration:
          #affinityGroup: together
          inputSteps:
            - name: updateVirtualRepositories
          integrations:
            - name: {{ .Values.jpdMain }}
            - name: {{ .Values.jpdDr }}
          cliPlugin: "{{ .Values.cliPlugin.name }}@{{ .Values.cliPlugin.version }}"
        execution:
          onExecute:
            - jf {{ .Values.cliPlugin.name }} -v
            - jf {{ .Values.cliPlugin.name }} delete remote {{ .Values.jpdMain }} {{ .Values.jpdDr }} --dry-run=false --inventory=true
          onSuccess:
            - cd $JF_PLUGIN_REPOSYNC_INVENTORY_PATH && ls -l       
            - mkdir {{ .Values.jpdDr }} && mv inventory*.yaml {{ .Values.jpdDr }}/
            - jf rt u {{ .Values.jpdDr }}/* $JFROG_CLI_PLUGINS_REPO/
            - rm -rf {{ .Values.jpdDr }}
      - name: deleteVirtualRepositories
        type: utils/bashV2
        configuration:
          #affinityGroup: together
          inputSteps:
            - name: deleteLocalRepositories
            - name: deleteRemoteRepositories
          integrations:
            - name: {{ .Values.jpdMain }}
            - name: {{ .Values.jpdDr }}
          cliPlugin: "{{ .Values.cliPlugin.name }}@{{ .Values.cliPlugin.version }}"
        execution:
          onExecute:
            - jf {{ .Values.cliPlugin.name }} -v
            - jf {{ .Values.cliPlugin.name }} delete virtual {{ .Values.jpdMain }} {{ .Values.jpdDr }} --dry-run=false --inventory=true
          onSuccess:
            - cd $JF_PLUGIN_REPOSYNC_INVENTORY_PATH && ls -l       
            - mkdir {{ .Values.jpdDr }} && mv inventory*.yaml {{ .Values.jpdDr }}/
            - jf rt u {{ .Values.jpdDr }}/* $JFROG_CLI_PLUGINS_REPO/
            - rm -rf {{ .Values.jpdDr }}   
      - name: DeleteProjects
        type: utils/bashV2
        configuration:
          #affinityGroup: together
          inputSteps:
            - name: deleteLocalRepositories
            - name: deleteRemoteRepositories
            - name: deleteVirtualRepositories
          integrations:
            - name: {{ .Values.jpdMain }}
            - name: {{ .Values.jpdDr }}
          cliPlugin: "{{ .Values.projectPlugin.name }}@{{ .Values.projectPlugin.version }}"     
        execution:
          onExecute:
            - /root/.jfrog/plugins/proj-sync/bin/{{ .Values.projectPlugin.name }} diff delete {{ .Values.jpdMain }} {{ .Values.jpdDr }}
